# Generated by Django 2.0.2 on 2018-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entretenimento',
            fields=[
                ('entretenimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('entretenimento_titulo', models.CharField(max_length=100)),
                ('entretenimento_capitulo', models.CharField(max_length=100)),
                ('entretenimento_temporada', models.CharField(max_length=100)),
                ('entretenimento_foto', models.CharField(max_length=100)),
                ('entretenimento_status', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
    ]
