# Generated by Django 2.0.2 on 2018-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('agua_id', models.AutoField(primary_key=True, serialize=False)),
                ('agua_meta', models.IntegerField()),
                ('agua_quantidade', models.IntegerField()),
            ],
        ),
    ]
