# Generated by Django 2.0.2 on 2018-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_agua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musculacao',
            fields=[
                ('musculacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('musculacao_dia', models.CharField(max_length=100)),
                ('musculacao_treino', models.CharField(max_length=100)),
                ('musculacao_exercicio', models.CharField(max_length=100)),
                ('musculacao_repeticoes', models.CharField(max_length=100)),
                ('musculacao_serie', models.CharField(max_length=100)),
                ('musculacao_pesso', models.CharField(max_length=100)),
            ],
        ),
    ]
